#!/usr/bin/env bash
# =============================================================================
# auto_bridge.sh — Antigravity MCP Auto-Bridge
# Detects local MCP server configuration files and maps their settings to
# the Antigravity environment. Run this script once after cloning or any
# time your MCP server configuration changes.
# =============================================================================

set -euo pipefail

# ── Colour helpers ────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${CYAN}[INFO]${RESET}  $*"; }
success() { echo -e "${GREEN}[OK]${RESET}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${RESET}  $*"; }
error()   { echo -e "${RED}[ERROR]${RESET} $*" >&2; }
header()  { echo -e "\n${BOLD}${CYAN}$*${RESET}\n"; }

# ── Constants ─────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_OUTPUT="${SCRIPT_DIR}/.env.mcp"
ANTIGRAVITY_CONFIG_DIR="${HOME}/.antigravity/mcp"
KNOWN_CONFIG_PATHS=(
  "${SCRIPT_DIR}/mcp.json"
  "${SCRIPT_DIR}/.mcp.json"
  "${SCRIPT_DIR}/mcp-config.json"
  "${HOME}/.config/mcp/config.json"
  "${HOME}/.mcp/config.json"
  "${HOME}/Library/Application Support/mcp/config.json"  # macOS
  "/etc/mcp/config.json"                                  # Linux system-wide
)

header "Antigravity MCP Auto-Bridge v1.0"

# ── 1. Detect project root ────────────────────────────────────────────────────
info "Project root: ${SCRIPT_DIR}"

# ── 2. Scan for MCP config files ─────────────────────────────────────────────
header "Scanning for MCP server configurations…"
FOUND_CONFIGS=()

for cfg in "${KNOWN_CONFIG_PATHS[@]}"; do
  if [[ -f "$cfg" ]]; then
    success "Found config: $cfg"
    FOUND_CONFIGS+=("$cfg")
  else
    info "No config at:  $cfg"
  fi
done

# Also check if a Claude / VS Code style mcp servers block exists
CLAUDE_CONFIG="${HOME}/Library/Application Support/Claude/claude_desktop_config.json"
if [[ -f "$CLAUDE_CONFIG" ]]; then
  success "Found Claude Desktop config: ${CLAUDE_CONFIG}"
  FOUND_CONFIGS+=("$CLAUDE_CONFIG")
fi

if [[ ${#FOUND_CONFIGS[@]} -eq 0 ]]; then
  warn "No existing MCP config files detected. Generating a default template."
fi

# ── 3. Detect Node / npx availability ────────────────────────────────────────
header "Checking runtime dependencies…"

if command -v node &>/dev/null; then
  NODE_VERSION="$(node --version)"
  success "Node.js: ${NODE_VERSION}"
else
  error "Node.js is not installed. Please install Node.js >= 18 to run MCP servers."
  exit 1
fi

if command -v npx &>/dev/null; then
  success "npx: $(npx --version)"
else
  error "npx not found. Install a recent version of npm."
  exit 1
fi

# ── 4. Detect built server ────────────────────────────────────────────────────
header "Checking build output…"
BUILT_SERVER="${SCRIPT_DIR}/dist/server.js"

if [[ -f "$BUILT_SERVER" ]]; then
  success "Built server found: ${BUILT_SERVER}"
  SERVER_CMD="node ${BUILT_SERVER}"
else
  warn "Built server not found at ${BUILT_SERVER}."
  warn "Run 'npm run build' first, or the bridge will use ts-node as a fallback."
  SERVER_CMD="npx ts-node ${SCRIPT_DIR}/src/server.ts"
fi

# ── 5. Write Antigravity environment file ────────────────────────────────────
header "Writing Antigravity MCP environment settings → ${ENV_OUTPUT}"

cat > "${ENV_OUTPUT}" <<EOF
# ============================================================
# Antigravity MCP Bridge — Environment Settings
# Auto-generated by auto_bridge.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Do NOT commit this file — add .env.mcp to .gitignore
# ============================================================

# The command Antigravity will use to launch the MCP server
MCP_SERVER_COMMAND="${SERVER_CMD}"

# Transport type (stdio | sse)
MCP_TRANSPORT=stdio

# Server identity
MCP_SERVER_NAME=antigravity-mcp-bridge
MCP_SERVER_VERSION=1.0.0

# Path to the skills directory (used by Antigravity Manager)
MCP_SKILLS_DIR=${SCRIPT_DIR}/skills

# Optional: default SQLite database for the sqlite_skill
# SQLITE_DB_PATH=/path/to/your/database.db

# Number of found config files (informational)
MCP_DETECTED_CONFIGS=${#FOUND_CONFIGS[@]}
EOF

success "Environment file written."

# ── 6. Ensure Antigravity config directory exists ────────────────────────────
header "Setting up Antigravity config directory…"
mkdir -p "${ANTIGRAVITY_CONFIG_DIR}"

BRIDGE_LINK="${ANTIGRAVITY_CONFIG_DIR}/antigravity-mcp-bridge.json"
cat > "${BRIDGE_LINK}" <<EOF
{
  "name": "antigravity-mcp-bridge",
  "version": "1.0.0",
  "transport": "stdio",
  "command": "${SERVER_CMD}",
  "skillsDir": "${SCRIPT_DIR}/skills",
  "envFile": "${ENV_OUTPUT}",
  "registeredAt": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
}
EOF
success "Bridge descriptor written to ${BRIDGE_LINK}"

# ── 7. Summary ────────────────────────────────────────────────────────────────
header "Summary"
echo -e "  ${BOLD}Configs detected:${RESET}  ${#FOUND_CONFIGS[@]}"
echo -e "  ${BOLD}Server command:${RESET}    ${SERVER_CMD}"
echo -e "  ${BOLD}Env file:${RESET}          ${ENV_OUTPUT}"
echo -e "  ${BOLD}Antigravity dir:${RESET}   ${ANTIGRAVITY_CONFIG_DIR}"
echo ""
success "Auto-bridge complete. You can now start Antigravity and import the sqlite_skill."
